### ISSUE TITLE
parsing failure with space after unquoted key

### ISSUE THREAD

**Issue by heywiki** [hjson/hjson-java#1]
## x : {},

throws "Found ' ' where a key name was expected". net.sf.json.JSONObject does parse this correctly however!

**Comment by heywiki** [comment]
As a note: i saw "fix trailing space in quoteless strings". I was using 1.1.2 from maven central, but still got this error.

**Comment by laktak** [comment]
Thanks, that's a good input. I'll take a look at it but it may take a few days. Let me know if you want to do a PR.

**Comment by heywiki** [comment]
Thanks, I stumbled upon this because I am currently reviewing the use of
Nashorn instead of Rhino JS, see
https://blogs.oracle.com/nashorn/entry/flexible_json_with_nashorn_parser.
Thanks alot for your implementation. I assume you are a german speaker? At
which company are you working at?

Cheers
Christoph

2015-12-03 16:30 GMT+01:00 Christian Zangl <notifications@github.com>:

**Comment by heywiki** [comment]
Just downloaded 1.1.3. Works. Thanks for the fix!
