### ISSUE TITLE
hjson requires closing curly bracket in its own line

### ISSUE THREAD

**Issue by heywiki** [hjson/hjson-java#11]
This works fine with json:
```
{foo:'bar'}
```
It throws the following in hjson (2.1.1)
```
org.hjson.ParseException: End of input while parsing an object (did you forget a closing '}'?) at 3:-1
	at org.hjson.HjsonParser.error(HjsonParser.java:482)
```

Only after you set the closing curly bracket in its own line, it works. My basic assumption is that hjson should be more forgiving than json. If hjson requires the closing bracket it its own line, than at least the error message is misleading.

**Comment by laktak** [comment]
This is because of the single quotes. It will be fixed soon but for now please use double quotes `"`. See #9.
