### ISSUE TITLE
whitespace between unquotedName and colon(:) causes ParseException

### ISSUE THREAD

**Issue by saijone** [hjson/hjson-java#3]
The bug can be reproduced by "{x :1}" as following:
        String js = "{x :1}"; //{123, 120, 32, 58, 49, 125}
        org.hjson.JsonValue jv = org.hjson.JsonValue.readHjson(js);

ParseException: Found ' ' where a key name was expected (check your syntax or use quotes if the key name includes {}[],: or whitespace) at 1:2

**Comment by saijone** [comment]
jackson with ALLOW_UNQUOTED_FIELD_NAMES correctly parses "{x :1}" ({123, 120, 32, 58, 49, 125}).

**Comment by saijone** [comment]
This seems to be a duplicate of #1 issue.

**Comment by laktak** [comment]
#1 & this is now fixed and should be in maven soon.
