### ISSUE TITLE
Version 3.0.1 not available in MVN repositories

### ISSUE THREAD

**Issue by afiller** [hjson/hjson-java#33]
Hello together, maybe it's just a matter of time OR the push have been forgotten, that's why I'm opening this ticket:

The new version 3.0.1 with the CVE fix is not available on mvnrepository.com - Has it been pushed?

Thanks in advance, I really like this library. We love using it in our projects! 👍

**Comment by trobro** [comment]
Hi, nice to hear you like this library! I'm working on publishing to Maven Central, it's been many years since the last release so there's some detective work required. :)

**Comment by afiller** [comment]
Perfect that you are working on it. Good luck with the detective work! 😁

**Comment by trobro** [comment]
Fixed, version 3.0.1 is now available in Maven.
