### ISSUE TITLE
Tabs in multiline string

### ISSUE THREAD

**Issue by hundera** [hjson/hjson-java#6]
When the string contains tabs (\t), it's not exported as a multiline string, but as JSON-string. That significantly impacts readability.

By HJSON syntax, there's to limit on tabs in the multiline string. Is it possible to export string with tabs as a multiline string?

thanks

**Comment by laktak** [comment]
Yes, this was recently fixed in [hjson-js](https://github.com/hjson/hjson-js/pull/15) as well. It should be enough to add `case '\t':` in `needsEscapeML` if you want to fix this yourself. I'll try to update it soon.
