### ISSUE TITLE
Parent/Owner

### ISSUE THREAD

**Issue by dhakehurst** [hjson/hjson-java#8]
I would like to be able to get the parent or owner JsonObject from a JsonValue.

would this be possible?

**Comment by laktak** [comment]
Since a JsonValue can be added to multiple parents this is not possible.

**Comment by dhakehurst** [comment]
Json is a tree,
therefore every node must have exactly one parent !

**Comment by laktak** [comment]
The JSON tree is only generated once you serialize the data. The Java objects can be added to multiple parents (e.g. when transforming data).
